//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Admin_System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio_Admin_System.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static bool Column1_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column10_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column10.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column11_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column11.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column2_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column2.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column3_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column3.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column4_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column4.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column5_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column5.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column6_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column6.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column7_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column7.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column8_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column8.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column9_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column9.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point dataDataSet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dataDataSet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point dataDataSetBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dataDataSetBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point formulaProvider1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("formulaProvider1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point formulaProvider2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("formulaProvider2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point fpSpread1_Sheet1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("fpSpread1_Sheet1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point fpSpread2_Sheet1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("fpSpread2_Sheet1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
